---
- name: "Stop instances"
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "./vars/{{ host_name }}.yaml"
  tasks:
    - name: "Stop instances"
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2_instance_id}}"
        region: "{{ region }}"
        state: stopped
        wait: True
        network:
          assign_public_ip: yes
        termination_protection: true

